import '../models/damage_type.dart';
import '../models/passive_counter.dart';
import '../models/passive_effect.dart';
import '../models/reactive_effect.dart';
import '../models/status_effect.dart';
import '../models/trigger.dart';
import '../models/unique_behavior.dart';
import '../util/dice.dart';

/// The built-in 72-Trigger catalog (60 active, 12 passive), a shared draft
/// pool any character may equip regardless of their own [CharacterType] -
/// nothing in the [Loadout] rules restricts equipping by type. The 60
/// active Triggers are balanced to exactly 20 melee / 20 ranged / 20
/// psychic by attack type (see the per-subtype distribution asserted in
/// the content-catalog tests), and include the 17 Unique-subtype Triggers
/// (5 melee, 2 ranged, 10 psychic) that wire the Phase C unique behaviors.
class TriggerCatalog {
  final Map<String, Trigger> _byId;

  TriggerCatalog._(this._byId);

  Trigger operator [](String id) {
    final trigger = _byId[id];
    if (trigger == null) throw ArgumentError('Unknown Trigger id: $id');
    return trigger;
  }

  bool contains(String id) => _byId.containsKey(id);

  Iterable<Trigger> get all => _byId.values;
  Iterable<ActiveTrigger> get activeTriggers => all.whereType<ActiveTrigger>();
  Iterable<PassiveTrigger> get passiveTriggers =>
      all.whereType<PassiveTrigger>();

  factory TriggerCatalog.builtIn() {
    final triggers = <Trigger>[
      ActiveTrigger(
        id: 'twin_fang_strike',
        name: 'Twin Fang Strike',
        category: TriggerCategory.attacker,
        equipCost: 20,
        trionCost: 10,
        cooldownTurns: 1,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.slashing,
        damage: const DiceExpression(2, 6, flatBonus: 37),
      ),
      ActiveTrigger(
        id: 'cleave',
        name: 'Cleave',
        category: TriggerCategory.attacker,
        equipCost: 24,
        trionCost: 15,
        cooldownTurns: 1,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.aoe,
        targetCount: 3,
        damageType: DamageType.slashing,
        damage: const DiceExpression(1, 6, flatBonus: 18),
      ),
      ActiveTrigger(
        id: 'suppressing_fire',
        name: 'Suppressing Fire',
        category: TriggerCategory.shooter,
        equipCost: 26,
        trionCost: 20,
        cooldownTurns: 2,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.burst,
        hitsPerUse: 3,
        targetCount: 2,
        damageType: DamageType.piercing,
        damage: const DiceExpression(1, 4, flatBonus: 16),
      ),
      ActiveTrigger(
        id: 'shatterpoint',
        name: 'Shatterpoint',
        category: TriggerCategory.trapper,
        equipCost: 18,
        trionCost: 12,
        cooldownTurns: 1,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.acid,
        damage: const DiceExpression(1, 6, flatBonus: 18),
        inflictedStatusEffects: const [StatusEffectApplication('corroded')],
      ),
      ActiveTrigger(
        id: 'venom_needle',
        name: 'Venom Needle',
        category: TriggerCategory.trapper,
        equipCost: 18,
        trionCost: 12,
        cooldownTurns: 1,
        originTag: OriginTag.afflict,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.poison,
        damage: const DiceExpression(1, 4, flatBonus: 12),
        inflictedStatusEffects: const [StatusEffectApplication('poisoned')],
      ),
      ActiveTrigger(
        id: 'dread_gaze',
        name: 'Dread Gaze',
        category: TriggerCategory.trapper,
        equipCost: 20,
        trionCost: 14,
        cooldownTurns: 1,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.psychic,
        damage: const DiceExpression(1, 4, flatBonus: 8),
        inflictedStatusEffects: const [StatusEffectApplication('terrified')],
      ),
      ActiveTrigger(
        id: 'charm_whisper',
        name: 'Charm Whisper',
        category: TriggerCategory.trapper,
        equipCost: 26,
        trionCost: 20,
        cooldownTurns: 2,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.single,
        inflictedStatusEffects: const [StatusEffectApplication('charmed')],
      ),
      // Rally Cry: converted from single to AoE in Phase D (team Inspire),
      // which also fills the melee AoE slot count for the 20/20/20 rebalance.
      ActiveTrigger(
        id: 'rally_cry',
        name: 'Rally Cry',
        category: TriggerCategory.optional,
        equipCost: 18,
        trionCost: 14,
        cooldownTurns: 2,
        originTag: OriginTag.energy,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.aoe,
        targetCount: 3,
        targetAffiliation: TargetAffiliation.ally,
        inflictedStatusEffects: const [StatusEffectApplication('inspired')],
      ),
      ActiveTrigger(
        id: 'war_chant',
        name: 'War Chant',
        category: TriggerCategory.optional,
        equipCost: 14,
        trionCost: 10,
        cooldownTurns: 2,
        originTag: OriginTag.energy,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        targetAffiliation: TargetAffiliation.self,
        inflictedStatusEffects: const [StatusEffectApplication('empowered')],
      ),
      ActiveTrigger(
        id: 'piercing_thrust',
        name: 'Piercing Thrust',
        category: TriggerCategory.attacker,
        equipCost: 22,
        trionCost: 14,
        cooldownTurns: 1,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.piercing,
        damage: const DiceExpression(2, 6, flatBonus: 45),
      ),
      ActiveTrigger(
        id: 'whirlwind_slash',
        name: 'Whirlwind Slash',
        category: TriggerCategory.attacker,
        equipCost: 20,
        trionCost: 12,
        cooldownTurns: 1,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.aoe,
        targetCount: 3,
        damageType: DamageType.slashing,
        damage: const DiceExpression(1, 4, flatBonus: 16),
      ),
      ActiveTrigger(
        id: 'longshot',
        name: 'Longshot',
        category: TriggerCategory.sniper,
        equipCost: 34,
        trionCost: 30,
        cooldownTurns: 2,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.piercing,
        damage: const DiceExpression(4, 8, flatBonus: 86),
      ),
      ActiveTrigger(
        id: 'scattershot',
        name: 'Scattershot',
        category: TriggerCategory.shooter,
        equipCost: 26,
        trionCost: 20,
        cooldownTurns: 2,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.burst,
        hitsPerUse: 4,
        targetCount: 2,
        damageType: DamageType.piercing,
        damage: const DiceExpression(1, 4, flatBonus: 8),
      ),
      ActiveTrigger(
        id: 'flashbang_round',
        name: 'Flashbang Round',
        category: TriggerCategory.trapper,
        equipCost: 22,
        trionCost: 18,
        cooldownTurns: 2,
        originTag: OriginTag.energy,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.aoe,
        targetCount: 3,
        inflictedStatusEffects: const [StatusEffectApplication('blinded')],
      ),
      ActiveTrigger(
        id: 'frost_lance',
        name: 'Frost Lance',
        category: TriggerCategory.attacker,
        equipCost: 22,
        trionCost: 14,
        cooldownTurns: 1,
        originTag: OriginTag.energy,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.cold,
        damage: const DiceExpression(1, 6, flatBonus: 18),
        inflictedStatusEffects: const [StatusEffectApplication('chilled')],
      ),
      ActiveTrigger(
        id: 'cinderburst',
        name: 'Cinderburst',
        category: TriggerCategory.attacker,
        equipCost: 26,
        trionCost: 18,
        cooldownTurns: 2,
        originTag: OriginTag.energy,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.aoe,
        targetCount: 3,
        damageType: DamageType.fire,
        damage: const DiceExpression(1, 6, flatBonus: 18),
        inflictedStatusEffects: const [StatusEffectApplication('scorched')],
      ),
      ActiveTrigger(
        id: 'acid_spray',
        name: 'Acid Spray',
        category: TriggerCategory.trapper,
        equipCost: 24,
        trionCost: 16,
        cooldownTurns: 2,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.aoe,
        targetCount: 3,
        damageType: DamageType.acid,
        damage: const DiceExpression(1, 4, flatBonus: 8),
        inflictedStatusEffects: const [StatusEffectApplication('corroded')],
      ),
      ActiveTrigger(
        id: 'nightmare_pulse',
        name: 'Nightmare Pulse',
        category: TriggerCategory.trapper,
        equipCost: 26,
        trionCost: 18,
        cooldownTurns: 2,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.aoe,
        targetCount: 3,
        damageType: DamageType.psychic,
        damage: const DiceExpression(1, 4, flatBonus: 8),
        inflictedStatusEffects: const [StatusEffectApplication('terrified')],
      ),
      ActiveTrigger(
        id: 'soul_siphon',
        name: 'Soul Siphon',
        category: TriggerCategory.attacker,
        equipCost: 24,
        trionCost: 16,
        cooldownTurns: 2,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.psychic,
        damage: const DiceExpression(1, 6, flatBonus: 18),
        healAmount: const DiceExpression(1, 4, flatBonus: -1),
        healsCasterInstead: true,
      ),
      ActiveTrigger(
        id: 'mind_shatter',
        name: 'Mind Shatter',
        category: TriggerCategory.trapper,
        equipCost: 24,
        trionCost: 18,
        cooldownTurns: 2,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.psychic,
        damage: const DiceExpression(1, 4, flatBonus: 8),
        inflictedStatusEffects: const [StatusEffectApplication('silenced')],
      ),
      ActiveTrigger(
        id: 'guardians_aegis',
        name: "Guardian's Aegis",
        category: TriggerCategory.optional,
        equipCost: 18,
        trionCost: 14,
        cooldownTurns: 2,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        targetAffiliation: TargetAffiliation.self,
        inflictedStatusEffects: const [
          StatusEffectApplication('guarded'),
          StatusEffectApplication('braced'),
        ],
      ),
      ActiveTrigger(
        id: 'cleansing_ward',
        name: 'Cleansing Ward',
        category: TriggerCategory.optional,
        equipCost: 22,
        trionCost: 16,
        cooldownTurns: 2,
        originTag: OriginTag.energy,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        targetAffiliation: TargetAffiliation.ally,
        inflictedStatusEffects: const [
          StatusEffectApplication('regenerating'),
          StatusEffectApplication('warded'),
        ],
      ),
      ActiveTrigger(
        id: 'predictive_parry',
        name: 'Predictive Parry',
        category: TriggerCategory.attacker,
        equipCost: 20,
        trionCost: 20,
        cooldownTurns: 2,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        targetAffiliation: TargetAffiliation.self,
        armsReactive: ReactiveKind.dodgeMeleeSingle,
      ),
      ActiveTrigger(
        id: 'numbing_toxin',
        name: 'Numbing Toxin',
        category: TriggerCategory.trapper,
        equipCost: 18,
        trionCost: 20,
        cooldownTurns: 2,
        originTag: OriginTag.afflict,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        targetAffiliation: TargetAffiliation.self,
        armsReactive: ReactiveKind.burstMitigation,
        armsReactiveDefaultTurns: 2,
      ),
      ActiveTrigger(
        id: 'root_snare',
        name: 'Root Snare',
        category: TriggerCategory.trapper,
        equipCost: 20,
        trionCost: 18,
        cooldownTurns: 2,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.bludgeoning,
        damage: const DiceExpression(1, 4, flatBonus: 8),
        inflictedStatusEffects: const [
          StatusEffectApplication('forced_repetition')
        ],
      ),
      ActiveTrigger(
        id: 'death_ledger',
        name: 'Death Ledger',
        category: TriggerCategory.trapper,
        equipCost: 20,
        trionCost: 18,
        cooldownTurns: 2,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.piercing,
        damage: const DiceExpression(1, 4, flatBonus: 8),
        armsReactive: ReactiveKind.nullifyAoe,
        armsReactiveDefaultTurns: 3,
      ),
      ActiveTrigger(
        id: 'scramble',
        name: 'Scramble',
        category: TriggerCategory.trapper,
        equipCost: 24,
        trionCost: 20,
        cooldownTurns: 2,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.psychic,
        damage: const DiceExpression(1, 4, flatBonus: 8),
        inflictedStatusEffects: const [StatusEffectApplication('misfire')],
      ),
      ActiveTrigger(
        id: 'stored_retribution',
        name: 'Stored Retribution',
        category: TriggerCategory.optional,
        equipCost: 18,
        trionCost: 16,
        cooldownTurns: 2,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        targetAffiliation: TargetAffiliation.self,
        armsReactive: ReactiveKind.bankDamage,
      ),
      ActiveTrigger(
        id: 'frozen_tempo',
        name: 'Frozen Tempo',
        category: TriggerCategory.optional,
        equipCost: 20,
        trionCost: 18,
        cooldownTurns: 2,
        originTag: OriginTag.energy,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        targetAffiliation: TargetAffiliation.self,
        armsReactive: ReactiveKind.cooldownSabotage,
        armsReactiveDefaultTurns: 2,
      ),

      // --- Phase D: Unique-subtype Triggers wiring the Phase C behaviors ---
      // Numbers here follow existing tuning conventions and are tunable.

      // Melee unique (5)
      ActiveTrigger(
        id: 'shared_agony',
        name: 'Shared Agony',
        category: TriggerCategory.attacker,
        equipCost: 24,
        trionCost: 12,
        cooldownTurns: 2,
        originTag: OriginTag.afflict,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.unique,
        uniqueBehavior: UniqueBehavior.sharedAgony,
        damageType: DamageType.necrotic,
        damage: const DiceExpression(2, 6, flatBonus: 40),
      ),
      ActiveTrigger(
        id: 'grave_bargain',
        name: 'Grave Bargain',
        category: TriggerCategory.attacker,
        equipCost: 22,
        trionCost: 8,
        cooldownTurns: 2,
        originTag: OriginTag.afflict,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.unique,
        uniqueBehavior: UniqueBehavior.graveBargain,
      ),
      ActiveTrigger(
        id: 'martyrs_end',
        name: "Martyr's End",
        category: TriggerCategory.attacker,
        equipCost: 28,
        trionCost: 10,
        cooldownTurns: 4,
        originTag: OriginTag.energy,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.unique,
        uniqueBehavior: UniqueBehavior.martyrsEnd,
        targetCount: 3,
      ),
      ActiveTrigger(
        id: 'vow_of_the_duel',
        name: 'Vow of the Duel',
        category: TriggerCategory.attacker,
        equipCost: 24,
        trionCost: 15,
        cooldownTurns: 3,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.unique,
        uniqueBehavior: UniqueBehavior.vowOfTheDuel,
      ),
      ActiveTrigger(
        id: 'sunder_arms',
        name: 'Sunder Arms',
        category: TriggerCategory.attacker,
        equipCost: 28,
        trionCost: 16,
        cooldownTurns: 3,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.unique,
        uniqueBehavior: UniqueBehavior.sunderArms,
        damageType: DamageType.slashing,
        damage: const DiceExpression(2, 6, flatBonus: 30),
      ),

      // Ranged unique (2)
      ActiveTrigger(
        id: 'curving_shot',
        name: 'Curving Shot',
        category: TriggerCategory.sniper,
        equipCost: 26,
        trionCost: 18,
        cooldownTurns: 2,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.unique,
        uniqueBehavior: UniqueBehavior.curvingShot,
        damageType: DamageType.piercing,
        damage: const DiceExpression(2, 6, flatBonus: 30),
      ),
      ActiveTrigger(
        id: 'called_shot',
        name: 'Called Shot',
        category: TriggerCategory.sniper,
        equipCost: 24,
        trionCost: 16,
        cooldownTurns: 2,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.unique,
        uniqueBehavior: UniqueBehavior.calledShot,
      ),

      // Psychic unique (10)
      ActiveTrigger(
        id: 'minds_eye',
        name: "Mind's Eye",
        category: TriggerCategory.optional,
        equipCost: 20,
        trionCost: 10,
        cooldownTurns: 3,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.unique,
        uniqueBehavior: UniqueBehavior.mindsEye,
      ),
      ActiveTrigger(
        id: 'forced_choice',
        name: 'Forced Choice',
        category: TriggerCategory.trapper,
        equipCost: 22,
        trionCost: 14,
        cooldownTurns: 2,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.unique,
        uniqueBehavior: UniqueBehavior.forcedChoice,
      ),
      ActiveTrigger(
        id: 'memory_theft',
        name: 'Memory Theft',
        category: TriggerCategory.trapper,
        equipCost: 24,
        trionCost: 16,
        cooldownTurns: 3,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.unique,
        uniqueBehavior: UniqueBehavior.memoryTheft,
      ),
      ActiveTrigger(
        id: 'sensory_swap',
        name: 'Sensory Swap',
        category: TriggerCategory.trapper,
        equipCost: 22,
        trionCost: 14,
        cooldownTurns: 2,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.unique,
        uniqueBehavior: UniqueBehavior.sensorySwap,
        targetCount: 2,
      ),
      ActiveTrigger(
        id: 'dread_resonance',
        name: 'Dread Resonance',
        category: TriggerCategory.attacker,
        equipCost: 26,
        trionCost: 18,
        cooldownTurns: 2,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.unique,
        uniqueBehavior: UniqueBehavior.dreadResonance,
        damageType: DamageType.psychic,
      ),
      ActiveTrigger(
        id: 'isolation',
        name: 'Isolation',
        category: TriggerCategory.trapper,
        equipCost: 22,
        trionCost: 14,
        cooldownTurns: 3,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.unique,
        uniqueBehavior: UniqueBehavior.isolation,
      ),
      ActiveTrigger(
        id: 'illusory_double',
        name: 'Illusory Double',
        category: TriggerCategory.optional,
        equipCost: 24,
        trionCost: 0,
        cooldownTurns: 2,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.unique,
        uniqueBehavior: UniqueBehavior.illusoryDouble,
        targetAffiliation: TargetAffiliation.ally,
      ),
      ActiveTrigger(
        id: 'echoing_doubt',
        name: 'Echoing Doubt',
        category: TriggerCategory.trapper,
        equipCost: 24,
        trionCost: 16,
        cooldownTurns: 3,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.unique,
        uniqueBehavior: UniqueBehavior.echoingDoubt,
      ),
      ActiveTrigger(
        id: 'karmic_bind',
        name: 'Karmic Bind',
        category: TriggerCategory.trapper,
        equipCost: 26,
        trionCost: 16,
        cooldownTurns: 3,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.unique,
        uniqueBehavior: UniqueBehavior.karmicBind,
      ),
      ActiveTrigger(
        id: 'unmaking',
        name: 'Unmaking',
        category: TriggerCategory.trapper,
        equipCost: 26,
        trionCost: 18,
        cooldownTurns: 3,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.unique,
        uniqueBehavior: UniqueBehavior.unmaking,
      ),

      // --- Phase D: 20/20/20 rebalance fillers (aoe + burst) ---

      // Ranged AoE (4)
      ActiveTrigger(
        id: 'frag_grenade',
        name: 'Frag Grenade',
        category: TriggerCategory.shooter,
        equipCost: 26,
        trionCost: 18,
        cooldownTurns: 2,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.aoe,
        targetCount: 3,
        damageType: DamageType.piercing,
        damage: const DiceExpression(1, 6, flatBonus: 16),
      ),
      ActiveTrigger(
        id: 'caustic_cloud',
        name: 'Caustic Cloud',
        category: TriggerCategory.trapper,
        equipCost: 24,
        trionCost: 16,
        cooldownTurns: 2,
        originTag: OriginTag.afflict,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.aoe,
        targetCount: 3,
        damageType: DamageType.acid,
        damage: const DiceExpression(1, 4, flatBonus: 8),
        inflictedStatusEffects: const [StatusEffectApplication('corroded')],
      ),
      ActiveTrigger(
        id: 'cryo_burst',
        name: 'Cryo Burst',
        category: TriggerCategory.attacker,
        equipCost: 26,
        trionCost: 18,
        cooldownTurns: 2,
        originTag: OriginTag.energy,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.aoe,
        targetCount: 3,
        damageType: DamageType.cold,
        damage: const DiceExpression(1, 6, flatBonus: 14),
        inflictedStatusEffects: const [StatusEffectApplication('chilled')],
      ),
      ActiveTrigger(
        id: 'thunderclap_round',
        name: 'Thunderclap Round',
        category: TriggerCategory.shooter,
        equipCost: 26,
        trionCost: 18,
        cooldownTurns: 2,
        originTag: OriginTag.energy,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.aoe,
        targetCount: 3,
        damageType: DamageType.thunder,
        damage: const DiceExpression(1, 4, flatBonus: 10),
        inflictedStatusEffects: const [StatusEffectApplication('overwhelmed')],
      ),

      // Ranged Burst (6)
      ActiveTrigger(
        id: 'rapid_fire',
        name: 'Rapid Fire',
        category: TriggerCategory.shooter,
        equipCost: 24,
        trionCost: 18,
        cooldownTurns: 2,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.burst,
        hitsPerUse: 3,
        targetCount: 1,
        damageType: DamageType.piercing,
        damage: const DiceExpression(1, 4, flatBonus: 14),
      ),
      ActiveTrigger(
        id: 'gatling_burst',
        name: 'Gatling Burst',
        category: TriggerCategory.shooter,
        equipCost: 28,
        trionCost: 24,
        cooldownTurns: 2,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.burst,
        hitsPerUse: 4,
        targetCount: 2,
        damageType: DamageType.piercing,
        damage: const DiceExpression(1, 4, flatBonus: 8),
      ),
      ActiveTrigger(
        id: 'split_shot',
        name: 'Split Shot',
        category: TriggerCategory.shooter,
        equipCost: 24,
        trionCost: 18,
        cooldownTurns: 2,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.burst,
        hitsPerUse: 2,
        targetCount: 2,
        damageType: DamageType.piercing,
        damage: const DiceExpression(1, 6, flatBonus: 10),
      ),
      ActiveTrigger(
        id: 'arc_volley',
        name: 'Arc Volley',
        category: TriggerCategory.shooter,
        equipCost: 26,
        trionCost: 20,
        cooldownTurns: 2,
        originTag: OriginTag.energy,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.burst,
        hitsPerUse: 3,
        targetCount: 2,
        damageType: DamageType.lightning,
        damage: const DiceExpression(1, 4, flatBonus: 10),
      ),
      ActiveTrigger(
        id: 'pepper_shot',
        name: 'Pepper Shot',
        category: TriggerCategory.shooter,
        equipCost: 22,
        trionCost: 16,
        cooldownTurns: 1,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.burst,
        hitsPerUse: 3,
        targetCount: 1,
        damageType: DamageType.piercing,
        damage: const DiceExpression(1, 4, flatBonus: 12),
      ),
      ActiveTrigger(
        id: 'venom_spray',
        name: 'Venom Spray',
        category: TriggerCategory.trapper,
        equipCost: 24,
        trionCost: 20,
        cooldownTurns: 2,
        originTag: OriginTag.afflict,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.burst,
        hitsPerUse: 3,
        targetCount: 2,
        damageType: DamageType.poison,
        damage: const DiceExpression(1, 4, flatBonus: 6),
        inflictedStatusEffects: const [StatusEffectApplication('poisoned')],
      ),

      // Psychic AoE (4)
      ActiveTrigger(
        id: 'psychic_scream',
        name: 'Psychic Scream',
        category: TriggerCategory.trapper,
        equipCost: 26,
        trionCost: 18,
        cooldownTurns: 2,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.aoe,
        targetCount: 3,
        damageType: DamageType.psychic,
        damage: const DiceExpression(1, 4, flatBonus: 8),
        inflictedStatusEffects: const [StatusEffectApplication('terrified')],
      ),
      ActiveTrigger(
        id: 'mind_fog',
        name: 'Mind Fog',
        category: TriggerCategory.trapper,
        equipCost: 24,
        trionCost: 16,
        cooldownTurns: 2,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.aoe,
        targetCount: 3,
        damageType: DamageType.psychic,
        damage: const DiceExpression(1, 4, flatBonus: 8),
        inflictedStatusEffects: const [StatusEffectApplication('blinded')],
      ),
      ActiveTrigger(
        id: 'mass_confusion',
        name: 'Mass Confusion',
        category: TriggerCategory.trapper,
        equipCost: 26,
        trionCost: 20,
        cooldownTurns: 2,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.aoe,
        targetCount: 3,
        damageType: DamageType.psychic,
        damage: const DiceExpression(1, 4, flatBonus: 8),
        inflictedStatusEffects: const [StatusEffectApplication('silenced')],
      ),
      ActiveTrigger(
        id: 'dread_wave',
        name: 'Dread Wave',
        category: TriggerCategory.attacker,
        equipCost: 26,
        trionCost: 18,
        cooldownTurns: 2,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.aoe,
        targetCount: 3,
        damageType: DamageType.psychic,
        damage: const DiceExpression(1, 6, flatBonus: 12),
        inflictedStatusEffects: const [StatusEffectApplication('overwhelmed')],
      ),

      PassiveTrigger(
        id: 'guardians_bulwark',
        name: "Guardian's Bulwark",
        category: TriggerCategory.optional,
        equipCost: 16,
        effect: const PassiveEffect(
          flatStatModifiers: {
            ModifiableStat.armor: 3,
            ModifiableStat.defense: 2
          },
        ),
      ),
      PassiveTrigger(
        id: 'iron_will',
        name: 'Iron Will',
        category: TriggerCategory.optional,
        equipCost: 14,
        effect: const PassiveEffect(
          flatStatModifiers: {ModifiableStat.statusEffectResistance: 5},
        ),
      ),
      PassiveTrigger(
        id: 'keen_eye',
        name: 'Keen Eye',
        category: TriggerCategory.optional,
        equipCost: 16,
        effect: const PassiveEffect(
          flatStatModifiers: {ModifiableStat.criticalChance: 8},
        ),
      ),
      PassiveTrigger(
        id: 'overcharged_core',
        name: 'Overcharged Core',
        category: TriggerCategory.optional,
        equipCost: 16,
        effect: const PassiveEffect(
          flatStatModifiers: {ModifiableStat.fatChance: 8},
        ),
      ),
      PassiveTrigger(
        id: 'vanguards_discipline',
        name: "Vanguard's Discipline",
        category: TriggerCategory.optional,
        equipCost: 22,
        effect: const PassiveEffect(
          flatStatModifiers: {
            ModifiableStat.armor: 5,
            ModifiableStat.defense: 4
          },
        ),
      ),
      PassiveTrigger(
        id: 'silver_tongue',
        name: 'Silver Tongue',
        category: TriggerCategory.optional,
        equipCost: 16,
        effect: const PassiveEffect(
          flatStatModifiers: {ModifiableStat.statusEffectInfliction: 6},
        ),
      ),
      PassiveTrigger(
        id: 'draegor',
        name: 'Draegor',
        category: TriggerCategory.optional,
        equipCost: 24,
        effect: const PassiveEffect(),
        counterKind: PassiveCounterKind.draegor,
      ),
      PassiveTrigger(
        id: 'nullhymn',
        name: 'Nullhymn',
        category: TriggerCategory.optional,
        equipCost: 26,
        effect: const PassiveEffect(),
        counterKind: PassiveCounterKind.nullhymn,
      ),
      PassiveTrigger(
        id: 'reckoning',
        name: 'Reckoning',
        category: TriggerCategory.optional,
        equipCost: 28,
        effect: const PassiveEffect(),
        counterKind: PassiveCounterKind.reckoning,
      ),
      PassiveTrigger(
        id: 'gravehour',
        name: 'Gravehour',
        category: TriggerCategory.optional,
        equipCost: 26,
        effect: const PassiveEffect(),
        counterKind: PassiveCounterKind.gravehour,
      ),
      PassiveTrigger(
        id: 'coldread',
        name: 'Coldread',
        category: TriggerCategory.optional,
        equipCost: 22,
        effect: const PassiveEffect(),
        counterKind: PassiveCounterKind.coldread,
      ),
      PassiveTrigger(
        id: 'ironvow',
        name: 'Ironvow',
        category: TriggerCategory.optional,
        equipCost: 24,
        effect: const PassiveEffect(),
        counterKind: PassiveCounterKind.ironvow,
      ),
    ];

    return TriggerCatalog._({for (final t in triggers) t.id: t});
  }

  static final TriggerCatalog defaultCatalog = TriggerCatalog.builtIn();
}
