import '../models/damage_type.dart';
import '../models/passive_effect.dart';
import '../models/reactive_effect.dart';
import '../models/status_effect.dart';
import '../models/trigger.dart';
import '../util/dice.dart';

/// The built-in 47-Trigger catalog (41 active, 6 passive), a shared draft
/// pool any character may equip regardless of their own [CharacterType] -
/// nothing in the [Loadout] rules restricts equipping by type.
class TriggerCatalog {
  final Map<String, Trigger> _byId;

  TriggerCatalog._(this._byId);

  Trigger operator [](String id) {
    final trigger = _byId[id];
    if (trigger == null) throw ArgumentError('Unknown Trigger id: $id');
    return trigger;
  }

  bool contains(String id) => _byId.containsKey(id);

  Iterable<Trigger> get all => _byId.values;
  Iterable<ActiveTrigger> get activeTriggers => all.whereType<ActiveTrigger>();
  Iterable<PassiveTrigger> get passiveTriggers =>
      all.whereType<PassiveTrigger>();

  factory TriggerCatalog.builtIn() {
    final triggers = <Trigger>[
      ActiveTrigger(
        id: 'twin_fang_strike',
        name: 'Twin Fang Strike',
        category: TriggerCategory.attacker,
        equipCost: 20,
        trionCost: 10,
        cooldownTurns: 1,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.slashing,
        damage: const DiceExpression(2, 6, flatBonus: 37),
      ),
      ActiveTrigger(
        id: 'cleave',
        name: 'Cleave',
        category: TriggerCategory.attacker,
        equipCost: 24,
        trionCost: 15,
        cooldownTurns: 1,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.aoe,
        targetCount: 3,
        damageType: DamageType.slashing,
        damage: const DiceExpression(1, 6, flatBonus: 18),
      ),
      ActiveTrigger(
        id: 'marksmans_volley',
        name: "Marksman's Volley",
        category: TriggerCategory.sniper,
        equipCost: 30,
        trionCost: 25,
        cooldownTurns: 2,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.piercing,
        damage: const DiceExpression(3, 8, flatBonus: 64),
      ),
      ActiveTrigger(
        id: 'suppressing_fire',
        name: 'Suppressing Fire',
        category: TriggerCategory.shooter,
        equipCost: 26,
        trionCost: 20,
        cooldownTurns: 2,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.burst,
        hitsPerUse: 3,
        targetCount: 2,
        damageType: DamageType.piercing,
        damage: const DiceExpression(1, 4, flatBonus: 16),
      ),
      ActiveTrigger(
        id: 'shatterpoint',
        name: 'Shatterpoint',
        category: TriggerCategory.trapper,
        equipCost: 18,
        trionCost: 12,
        cooldownTurns: 1,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.acid,
        damage: const DiceExpression(1, 6, flatBonus: 18),
        inflictedStatusEffects: const [StatusEffectApplication('corroded')],
      ),
      ActiveTrigger(
        id: 'venom_needle',
        name: 'Venom Needle',
        category: TriggerCategory.trapper,
        equipCost: 18,
        trionCost: 12,
        cooldownTurns: 1,
        originTag: OriginTag.afflict,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.poison,
        damage: const DiceExpression(1, 4, flatBonus: 12),
        inflictedStatusEffects: const [StatusEffectApplication('poisoned')],
      ),
      ActiveTrigger(
        id: 'binding_snare',
        name: 'Binding Snare',
        category: TriggerCategory.trapper,
        equipCost: 18,
        trionCost: 12,
        cooldownTurns: 1,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.bludgeoning,
        damage: const DiceExpression(1, 4, flatBonus: 8),
        inflictedStatusEffects: const [StatusEffectApplication('slowed')],
      ),
      ActiveTrigger(
        id: 'mind_spike',
        name: 'Mind Spike',
        category: TriggerCategory.attacker,
        equipCost: 24,
        trionCost: 18,
        cooldownTurns: 2,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.unique,
        damageType: DamageType.psychic,
        damage: const DiceExpression(2, 6, flatBonus: 29),
        inflictedStatusEffects: const [StatusEffectApplication('overwhelmed')],
      ),
      ActiveTrigger(
        id: 'dread_gaze',
        name: 'Dread Gaze',
        category: TriggerCategory.trapper,
        equipCost: 20,
        trionCost: 14,
        cooldownTurns: 1,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.psychic,
        damage: const DiceExpression(1, 4, flatBonus: 8),
        inflictedStatusEffects: const [StatusEffectApplication('terrified')],
      ),
      ActiveTrigger(
        id: 'charm_whisper',
        name: 'Charm Whisper',
        category: TriggerCategory.trapper,
        equipCost: 26,
        trionCost: 20,
        cooldownTurns: 2,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.single,
        inflictedStatusEffects: const [StatusEffectApplication('charmed')],
      ),
      ActiveTrigger(
        id: 'mending_light',
        name: 'Mending Light',
        category: TriggerCategory.optional,
        equipCost: 20,
        trionCost: 15,
        cooldownTurns: 1,
        originTag: OriginTag.energy,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        targetAffiliation: TargetAffiliation.ally,
        healAmount: const DiceExpression(2, 4, flatBonus: -2),
      ),
      ActiveTrigger(
        id: 'vital_surge',
        name: 'Vital Surge',
        category: TriggerCategory.optional,
        equipCost: 18,
        trionCost: 15,
        cooldownTurns: 2,
        originTag: OriginTag.energy,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        targetAffiliation: TargetAffiliation.ally,
        inflictedStatusEffects: const [StatusEffectApplication('regenerating')],
      ),
      ActiveTrigger(
        id: 'rally_cry',
        name: 'Rally Cry',
        category: TriggerCategory.optional,
        equipCost: 16,
        trionCost: 12,
        cooldownTurns: 2,
        originTag: OriginTag.energy,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        targetAffiliation: TargetAffiliation.ally,
        inflictedStatusEffects: const [StatusEffectApplication('inspired')],
      ),
      ActiveTrigger(
        id: 'war_chant',
        name: 'War Chant',
        category: TriggerCategory.optional,
        equipCost: 14,
        trionCost: 10,
        cooldownTurns: 2,
        originTag: OriginTag.energy,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        targetAffiliation: TargetAffiliation.self,
        inflictedStatusEffects: const [StatusEffectApplication('empowered')],
      ),
      ActiveTrigger(
        id: 'fortify',
        name: 'Fortify',
        category: TriggerCategory.optional,
        equipCost: 14,
        trionCost: 10,
        cooldownTurns: 2,
        originTag: OriginTag.energy,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        targetAffiliation: TargetAffiliation.self,
        inflictedStatusEffects: const [StatusEffectApplication('guarded')],
      ),
      ActiveTrigger(
        id: 'adrenal_rush',
        name: 'Adrenal Rush',
        category: TriggerCategory.optional,
        equipCost: 14,
        trionCost: 10,
        cooldownTurns: 2,
        originTag: OriginTag.energy,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        targetAffiliation: TargetAffiliation.self,
        inflictedStatusEffects: const [StatusEffectApplication('hastened')],
      ),
      ActiveTrigger(
        id: 'piercing_thrust',
        name: 'Piercing Thrust',
        category: TriggerCategory.attacker,
        equipCost: 22,
        trionCost: 14,
        cooldownTurns: 1,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.piercing,
        damage: const DiceExpression(2, 6, flatBonus: 45),
      ),
      ActiveTrigger(
        id: 'whirlwind_slash',
        name: 'Whirlwind Slash',
        category: TriggerCategory.attacker,
        equipCost: 20,
        trionCost: 12,
        cooldownTurns: 1,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.aoe,
        targetCount: 3,
        damageType: DamageType.slashing,
        damage: const DiceExpression(1, 4, flatBonus: 16),
      ),
      ActiveTrigger(
        id: 'longshot',
        name: 'Longshot',
        category: TriggerCategory.sniper,
        equipCost: 34,
        trionCost: 30,
        cooldownTurns: 2,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.piercing,
        damage: const DiceExpression(4, 8, flatBonus: 86),
      ),
      ActiveTrigger(
        id: 'scattershot',
        name: 'Scattershot',
        category: TriggerCategory.shooter,
        equipCost: 26,
        trionCost: 20,
        cooldownTurns: 2,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.burst,
        hitsPerUse: 4,
        targetCount: 2,
        damageType: DamageType.piercing,
        damage: const DiceExpression(1, 4, flatBonus: 8),
      ),
      ActiveTrigger(
        id: 'flashbang_round',
        name: 'Flashbang Round',
        category: TriggerCategory.trapper,
        equipCost: 22,
        trionCost: 18,
        cooldownTurns: 2,
        originTag: OriginTag.energy,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.aoe,
        targetCount: 3,
        inflictedStatusEffects: const [StatusEffectApplication('blinded')],
      ),
      ActiveTrigger(
        id: 'frost_lance',
        name: 'Frost Lance',
        category: TriggerCategory.attacker,
        equipCost: 22,
        trionCost: 14,
        cooldownTurns: 1,
        originTag: OriginTag.energy,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.cold,
        damage: const DiceExpression(1, 6, flatBonus: 18),
        inflictedStatusEffects: const [StatusEffectApplication('chilled')],
      ),
      ActiveTrigger(
        id: 'cinderburst',
        name: 'Cinderburst',
        category: TriggerCategory.attacker,
        equipCost: 26,
        trionCost: 18,
        cooldownTurns: 2,
        originTag: OriginTag.energy,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.aoe,
        targetCount: 3,
        damageType: DamageType.fire,
        damage: const DiceExpression(1, 6, flatBonus: 18),
        inflictedStatusEffects: const [StatusEffectApplication('scorched')],
      ),
      ActiveTrigger(
        id: 'static_discharge',
        name: 'Static Discharge',
        category: TriggerCategory.attacker,
        equipCost: 22,
        trionCost: 14,
        cooldownTurns: 1,
        originTag: OriginTag.energy,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.lightning,
        damage: const DiceExpression(1, 8, flatBonus: 22),
        inflictedStatusEffects: const [StatusEffectApplication('overwhelmed')],
      ),
      ActiveTrigger(
        id: 'acid_spray',
        name: 'Acid Spray',
        category: TriggerCategory.trapper,
        equipCost: 24,
        trionCost: 16,
        cooldownTurns: 2,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.aoe,
        targetCount: 3,
        damageType: DamageType.acid,
        damage: const DiceExpression(1, 4, flatBonus: 8),
        inflictedStatusEffects: const [StatusEffectApplication('corroded')],
      ),
      ActiveTrigger(
        id: 'nightmare_pulse',
        name: 'Nightmare Pulse',
        category: TriggerCategory.trapper,
        equipCost: 26,
        trionCost: 18,
        cooldownTurns: 2,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.aoe,
        targetCount: 3,
        damageType: DamageType.psychic,
        damage: const DiceExpression(1, 4, flatBonus: 8),
        inflictedStatusEffects: const [StatusEffectApplication('terrified')],
      ),
      ActiveTrigger(
        id: 'soul_siphon',
        name: 'Soul Siphon',
        category: TriggerCategory.attacker,
        equipCost: 24,
        trionCost: 16,
        cooldownTurns: 2,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.psychic,
        damage: const DiceExpression(1, 6, flatBonus: 18),
        healAmount: const DiceExpression(1, 4, flatBonus: -1),
        healsCasterInstead: true,
      ),
      ActiveTrigger(
        id: 'mind_shatter',
        name: 'Mind Shatter',
        category: TriggerCategory.trapper,
        equipCost: 24,
        trionCost: 18,
        cooldownTurns: 2,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.psychic,
        damage: const DiceExpression(1, 4, flatBonus: 8),
        inflictedStatusEffects: const [StatusEffectApplication('silenced')],
      ),
      ActiveTrigger(
        id: 'guardians_aegis',
        name: "Guardian's Aegis",
        category: TriggerCategory.optional,
        equipCost: 18,
        trionCost: 14,
        cooldownTurns: 2,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        targetAffiliation: TargetAffiliation.self,
        inflictedStatusEffects: const [
          StatusEffectApplication('guarded'),
          StatusEffectApplication('braced'),
        ],
      ),
      ActiveTrigger(
        id: 'second_wind',
        name: 'Second Wind',
        category: TriggerCategory.optional,
        equipCost: 16,
        trionCost: 12,
        cooldownTurns: 2,
        originTag: OriginTag.energy,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        targetAffiliation: TargetAffiliation.self,
        inflictedStatusEffects: const [StatusEffectApplication('regenerating')],
      ),
      ActiveTrigger(
        id: 'bloodpact',
        name: 'Bloodpact',
        category: TriggerCategory.optional,
        equipCost: 14,
        trionCost: 10,
        cooldownTurns: 2,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        targetAffiliation: TargetAffiliation.self,
        inflictedStatusEffects: const [StatusEffectApplication('enraged')],
      ),
      ActiveTrigger(
        id: 'marked_for_death',
        name: 'Marked for Death',
        category: TriggerCategory.trapper,
        equipCost: 18,
        trionCost: 12,
        cooldownTurns: 1,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.piercing,
        damage: const DiceExpression(1, 4, flatBonus: 8),
        inflictedStatusEffects: const [StatusEffectApplication('marked')],
      ),
      ActiveTrigger(
        id: 'battle_cry',
        name: 'Battle Cry',
        category: TriggerCategory.optional,
        equipCost: 16,
        trionCost: 12,
        cooldownTurns: 2,
        originTag: OriginTag.energy,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        targetAffiliation: TargetAffiliation.ally,
        inflictedStatusEffects: const [StatusEffectApplication('empowered')],
      ),
      ActiveTrigger(
        id: 'cleansing_ward',
        name: 'Cleansing Ward',
        category: TriggerCategory.optional,
        equipCost: 22,
        trionCost: 16,
        cooldownTurns: 2,
        originTag: OriginTag.energy,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        targetAffiliation: TargetAffiliation.ally,
        inflictedStatusEffects: const [
          StatusEffectApplication('regenerating'),
          StatusEffectApplication('warded'),
        ],
      ),
      ActiveTrigger(
        id: 'predictive_parry',
        name: 'Predictive Parry',
        category: TriggerCategory.attacker,
        equipCost: 20,
        trionCost: 20,
        cooldownTurns: 2,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        targetAffiliation: TargetAffiliation.self,
        armsReactive: ReactiveKind.dodgeMeleeSingle,
      ),
      ActiveTrigger(
        id: 'numbing_toxin',
        name: 'Numbing Toxin',
        category: TriggerCategory.trapper,
        equipCost: 18,
        trionCost: 20,
        cooldownTurns: 2,
        originTag: OriginTag.afflict,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        targetAffiliation: TargetAffiliation.self,
        armsReactive: ReactiveKind.burstMitigation,
        armsReactiveDefaultTurns: 2,
      ),
      ActiveTrigger(
        id: 'root_snare',
        name: 'Root Snare',
        category: TriggerCategory.trapper,
        equipCost: 20,
        trionCost: 18,
        cooldownTurns: 2,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.bludgeoning,
        damage: const DiceExpression(1, 4, flatBonus: 8),
        inflictedStatusEffects: const [
          StatusEffectApplication('forced_repetition')
        ],
      ),
      ActiveTrigger(
        id: 'death_ledger',
        name: 'Death Ledger',
        category: TriggerCategory.trapper,
        equipCost: 20,
        trionCost: 18,
        cooldownTurns: 2,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.ranged,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.piercing,
        damage: const DiceExpression(1, 4, flatBonus: 8),
        armsReactive: ReactiveKind.nullifyAoe,
        armsReactiveDefaultTurns: 3,
      ),
      ActiveTrigger(
        id: 'scramble',
        name: 'Scramble',
        category: TriggerCategory.trapper,
        equipCost: 24,
        trionCost: 20,
        cooldownTurns: 2,
        originTag: OriginTag.mental,
        rangeTag: RangeTag.ranged,
        attackType: AttackType.psychic,
        attackSubtype: AttackSubtype.single,
        damageType: DamageType.psychic,
        damage: const DiceExpression(1, 4, flatBonus: 8),
        inflictedStatusEffects: const [StatusEffectApplication('misfire')],
      ),
      ActiveTrigger(
        id: 'stored_retribution',
        name: 'Stored Retribution',
        category: TriggerCategory.optional,
        equipCost: 18,
        trionCost: 16,
        cooldownTurns: 2,
        originTag: OriginTag.physical,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        targetAffiliation: TargetAffiliation.self,
        armsReactive: ReactiveKind.bankDamage,
      ),
      ActiveTrigger(
        id: 'frozen_tempo',
        name: 'Frozen Tempo',
        category: TriggerCategory.optional,
        equipCost: 20,
        trionCost: 18,
        cooldownTurns: 2,
        originTag: OriginTag.energy,
        rangeTag: RangeTag.melee,
        attackType: AttackType.melee,
        attackSubtype: AttackSubtype.single,
        targetAffiliation: TargetAffiliation.self,
        armsReactive: ReactiveKind.cooldownSabotage,
        armsReactiveDefaultTurns: 2,
      ),
      PassiveTrigger(
        id: 'guardians_bulwark',
        name: "Guardian's Bulwark",
        category: TriggerCategory.optional,
        equipCost: 16,
        effect: const PassiveEffect(
          flatStatModifiers: {
            ModifiableStat.armor: 3,
            ModifiableStat.defense: 2
          },
        ),
      ),
      PassiveTrigger(
        id: 'iron_will',
        name: 'Iron Will',
        category: TriggerCategory.optional,
        equipCost: 14,
        effect: const PassiveEffect(
          flatStatModifiers: {ModifiableStat.statusEffectResistance: 5},
        ),
      ),
      PassiveTrigger(
        id: 'keen_eye',
        name: 'Keen Eye',
        category: TriggerCategory.optional,
        equipCost: 16,
        effect: const PassiveEffect(
          flatStatModifiers: {ModifiableStat.criticalChance: 8},
        ),
      ),
      PassiveTrigger(
        id: 'overcharged_core',
        name: 'Overcharged Core',
        category: TriggerCategory.optional,
        equipCost: 16,
        effect: const PassiveEffect(
          flatStatModifiers: {ModifiableStat.fatChance: 8},
        ),
      ),
      PassiveTrigger(
        id: 'vanguards_discipline',
        name: "Vanguard's Discipline",
        category: TriggerCategory.optional,
        equipCost: 22,
        effect: const PassiveEffect(
          flatStatModifiers: {
            ModifiableStat.armor: 5,
            ModifiableStat.defense: 4
          },
        ),
      ),
      PassiveTrigger(
        id: 'silver_tongue',
        name: 'Silver Tongue',
        category: TriggerCategory.optional,
        equipCost: 16,
        effect: const PassiveEffect(
          flatStatModifiers: {ModifiableStat.statusEffectInfliction: 6},
        ),
      ),
    ];

    return TriggerCatalog._({for (final t in triggers) t.id: t});
  }

  static final TriggerCatalog defaultCatalog = TriggerCatalog.builtIn();
}
